### ISSUE TITLE
No module named argparse + ValueError: zero length field name in format

### ISSUE THREAD

**Issue by slrslr** [adrianherrera/virustotal#1]
**# python vt_driver.py file-scan -h**

```
Traceback (most recent call last):
  File "vt_driver.py", line 16, in <module>
    import argparse
ImportError: No module named argparse
```

**# easy_install argparse**

**# vt_driver.py file-scan /root/postfix-delete.pl**

```
Traceback (most recent call last):
  File "/usr/bin/vt_driver.py", line 5, in <module>
    pkg_resources.run_script('VirusTotal==0.10', 'vt_driver.py')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/VirusTotal-0.10-py2.6.egg/EGG-INFO/scripts/vt_driver.py", line 454, in <module>
    main()
  File "/usr/lib/python2.6/site-packages/VirusTotal-0.10-py2.6.egg/EGG-INFO/scripts/vt_driver.py", line 418, in main
    api_key = _parse_config(config_file)
  File "/usr/lib/python2.6/site-packages/VirusTotal-0.10-py2.6.egg/EGG-INFO/scripts/vt_driver.py", line 175, in _parse_config
    _error('Config file \'{}\' does not exist'.format(conf_file))
ValueError: zero length field name in format
```

Please how can i fix this?

**Comment by adrianherrera** [comment]
Hey there!

I think I know what the problem is. So the script takes an optional `--config` parameter that takes the path to a config file. This config file is formatted as follows:

```
[vt]
apikey: <your API key goes here>
```

If you don't provide this option, then by default the script will look for the config file at `$HOME/.vtapi`. However, I now realise this is not explained anywhere in the README, so I will fix this!

Any further problems please let me know.
